builders:
  preflistGeneratorBuilder:
    import: 'package:preflist_generator/generators.dart'
    builder_factories: ['preflistGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".preflist.g.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]