name: preflist_generator
description: Scrapes a dart file for preferences and puts them into a list
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6