name: flutter_tqr
description: Generates random tableaus for Thunderstone Quest

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  package_info_plus: ^1.0.3
  analyzer: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  source_gen: ^1.0.2
  preflist_generator:
    path: preflist_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # Required for localization support.
  # See https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cards.yaml
    - assets/dice_white.png
    - assets/dice_black.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant-Regular.ttf
        - asset: assets/fonts/Cormorant-Bold.ttf
          weight: 700
    - family: CormorantSC
      fonts:
        - asset: assets/fonts/CormorantSC-Regular.ttf
