name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Download Dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build

      - name: Run Unit Tests
        run: flutter test

      - name: Build
        run: flutter build web

      - name: Fix service worker for GitHub Pages
        run: sed -i '/ \"\/\",$/d' build/web/flutter_service_worker.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'